markdown: redcarpet

highlighter: pygments
permalink: /:title

redcarpet:
  extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

url: http://renchunxiao.github.io/
baseurl: /rcxblog.github.io

sass:
  sass_dir: public/css
  style: :compressed

github: renchunxiao
author: chunxiaoren
