markdown: redcarpet
highlighter: null
permalink: /:title
pygments: true

url: http://renchunxiao.github.io/
baseurl: /rcxblog.github.io

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed

