markdown: redcarpet
highlighter: null
permalink: /:title

url: http://renchunxiao.github.io/
baseurl: /rcxblog.github.io

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed

comments :
  provider : duoshuo
  duoshuo :
    short_name : liberize
  disqus :
      short_name : liberize
