markdown: redcarpet
highlighter: null
permalink: /:title

url: http://renchunxiao.github.io/
baseurl:http://renchunxiao.github.io/rcxblog.github.io

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
