markdown: redcarpet

highlighter: pygments
permalink: /:title

redcarpet:
  extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

url: http://renchx.com/

sass:
  sass_dir: public/css
  style: :compressed

github: renchunxiao
author: chunxiaoren

name: 任春晓的Blog
description: 学习笔记以及对各种语言的理解
